[Setup]
AppName=Kodair Browser
AppVersion=1.0.1
DefaultDirName={autopf}\Kodair
; `PrivilegesRequired=lowest` is the magic flag! 
; It forces the installer to run without requiring Admin rights,
; and installs the app inside the user's Local AppData directory.
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=KodairInstaller
Compression=lzma2
SolidCompression=yes
SetupIconFile=kodair_browser\windows\runner\resources\app_icon.ico

[Files]
; This bundles all the files generated by `flutter build windows`
Source: "kodair_browser\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Creates a Desktop and Start Menu shortcut for the user
Name: "{autoprograms}\Kodair"; Filename: "{app}\kodair_browser.exe"
Name: "{autodesktop}\Kodair"; Filename: "{app}\kodair_browser.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked